website/package-lock.json
Updated node modules because of severe vulnerabilities
=> chore: updated node modules because of severe vulnerabilities

docs/backend/build-and-load-docker-image.md, docs/backend/file-permissions.md, docs/backend/install-and-running-locally.md, docs/backend/install-and-running-on-server.md, docs/backend/nginx.md, docs/backend/service-configuration.md
=> feat: added liveservice documentation

docs/backend/service-configuration.md
=> feat: adapt service configurations for live messaging

docs/backend/service-configuration.md
=> feat: adapt service configurations for draft messages

docs/backend/build-and-load-docker-image.md, docs/backend/service-configuration.md
=> feat: adapt hint messages for upcoming service configurations

docs/backend/first-start.md
- changed path to user-add file due to Keycloak update
=> feat: changed path due to keycloak update

docs/backend/first-start.md, docs/backend/install-and-running-locally.md, docs/backend/install-and-running-on-server.md, docs/backend/openldap-configuration.md
- improved documentation after fresh installation
- fixed typos
- updated descriptions
=> feat: Improved documentation

docs/backend/first-start.md
=> Feature add commands for replica set

docs/backend/first-start.md, docs/backend/install-and-running-locally.md, docs/backend/openldap-configuration.md, docs/backend/service-configuration.md
=> docs documentation improvements

docs/releases/agencyservice.md
=> feat: remove unused roles

docs/backend/service-configuration.md
Add information for synchronized user data.
=> docs: add information for synchronized user data

.github/workflows/publish.yml, Readme.md, docs/backend/build-and-load-docker-image.md, docs/backend/first-start.md, docs/backend/install-and-running-locally.md, docs/backend/install-and-running-on-server.md, docs/backend/openldap-configuration.md, docs/backend/service-configuration.md, docs/backend/starting-and-stopping-the-services.md, docs/releases/adminer.md, docs/releases/agencyservice.md, docs/releases/frontend.md, docs/releases/keycloak.md, docs/releases/liveservice.md, docs/releases/mailservice.md, docs/releases/mariadb.md, docs/releases/messageservice.md, docs/releases/mongodb.md, docs/releases/nginx.md, docs/releases/nosqlclient.md, docs/releases/openldap.md, docs/releases/overview.md, docs/releases/rocketchat.md, docs/releases/uploadservice.md, docs/releases/userservice.md, docs/releases/versionhistory.md, docs/setup/set-up-frontend.md, website/sidebars.json
=> Release 2020-11-24

docs/releases/uploadservice.md
=> feat: integration of uploadservice file restriction

docs/releases/agencyservice.md
Add release notes for agencyservice
=> feat: added release notes for create agency admin api

docs/releases/agencyservice.md
Added release notes for create agency admin api
=> feat: added release notes for update agency admin api

docs/releases/userservice.md
=> feat: adapt documentation for update consultant admin api

docs/releases/agencyservice.md
=> feat: adapt documentation for update admin agency api

website/package-lock.json, website/package.json
- fixes vulnerability on dependencies
=> chore: 🤖 update dependency for security

docs/backend/build-and-load-docker-image.md, docs/backend/file-permissions.md, docs/backend/install-and-running-locally.md, docs/backend/install-and-running-on-server.md, docs/backend/login-data-access-links.md, docs/backend/nginx.md, docs/backend/service-configuration.md, docs/releases/videoservice.md
Added documentation for new VideoService
=> docs: added documentation for new video service

docs/backend/videoBackend-lokal.md, website/sidebars.json
Add videoBackend dokumentation
- New page for videoBackend installation & configuration
- Add the new page to existing structure
=> feat: add a page for the videoBackend installation

docs/backend/service-configuration.md, docs/releases/videoservice.md
Added the installation and configuration documentation for the new VideoService.
=> Add VideoService

docs/backend/videobackend.md
- adds additional info for usage behind a NAT
=> feat: add description for use behind NAT

docs/backend/service-configuration.md
=> feat: adapt documentation for video service configuration

website/package-lock.json, website/package.json
- added conflicting dependency `immer` as security update
=> chore: 🤖 fixed conflicting dependency

docs/frontend/build.md, docs/frontend/testing.md, website/sidebars.json
-  add cypress description to docu
=> docs: ✏️ add cypress to docu

Readme.md
- added information about the automated publication of the documentation to github pages
=> docs: ✏️ added info about automated docu publication in readme

docs/releases/videobackend.md, docs/releases/videoservice.md
Added hint that video calls are currently deactivated
=> docs: added hint that video calls are currently deactivated

docs/releases/agencyservice.md, docs/releases/frontend.md, docs/releases/mailservice.md, docs/releases/overview.md, docs/releases/uploadservice.md, docs/releases/userservice.md, docs/releases/versionhistory.md
=> feat: adapt release documentation

docs/backend/cors-configuration.md, docs/backend/first-start.md, docs/backend/install-and-running-locally.md, docs/backend/install-and-running-on-server.md, docs/backend/service-configuration.md, website/package-lock.json, website/package.json, website/sidebars.json
Added information for CORS settings.
=> Feature add cors info

docs/releases/userservice.md
=> feat: release documentation for push notifications

docs/backend/service-configuration.md, docs/releases/keycloak.md, docs/releases/nginx.md, docs/releases/rocketchat.md, docs/releases/userservice.md
Adapted release and update documentation for recent changes.
=> feat: adapted release and update documentation for recent changes

docs/releases/backend.md, docs/releases/versionhistory.md
Add release information for nginx configuration changes
=> feat: added release information for nginx configuration

docs/releases/backend.md, docs/releases/versionhistory.md
Add release information for backend
=> Feat removed obsolete tls versions from nginx ssl configuration

docs/backend/admin-api.md, docs/backend/login-data-access-links.md, website/package-lock.json, website/package.json, website/sidebars.json
Added admin api documentation.
=> feat: added admin api documentation

docs/releases/userservice.md
=> feat: keycloak role migration group chat

docs/general/browser-matrix.md
- remove ie from browser matrix
=> docs: ✏️ remove internet explorer from browser matrix

docs/releases/userservice.md
=> feat: add conversations api

docs/backend/service-configuration.md
Added env. variables for the AgencyService, UserService and MailService update
=> feat: added new env variables to the documentation

docs/backend/first-start.md
Fix of an incorrect database specification for the NOSqlClient configuration
=> fix incorrect database specification changed

docs/releases/userservice.md
=> feat: added permission to rocket chat

docs/releases/consultingtypeservice.md, website/sidebars.json
Added consulting type service to sidebar
=> docs: added consulting type service to sidebar

docs/backend/service-configuration.md, docs/releases/userservice.md
=> feat: added keycloak properties

docs/releases/adminer.md, docs/releases/keycloak.md, docs/releases/mariadb.md, docs/releases/nginx.md, docs/releases/rocketchat.md
- RocketChat
- Adminer
- Keycloak
- MariaDB
- Nginx
=> feat: update open source components

docs/releases/consultingtypeservice.md, docs/releases/frontend.md, docs/releases/keycloak.md, docs/releases/liveservice.md, docs/releases/overview.md, docs/releases/versionhistory.md
=> docs: release documentation

docs/releases/keycloak.md
Added missing location for password reset
=> docs: added missing location for password reset

docs/backend/cors-configuration.md
=> feat: adapt cors configuration

docs/backend/starting-and-stopping-the-services.md, docs/frontend/testing.md, docs/frontend/tools.md, docs/setup/set-up-frontend.md
Update for local FE development
=> docs: update setup for local FE development

docs/setup/set-up-frontend.md
- explaining the two options for local frontend development
=> feat: 🎸 add local frontend to dev setup

docs/releases/agencyservice.md, docs/releases/consultingtypeservice.md, docs/releases/frontend.md, docs/releases/overview.md, docs/releases/uploadservice.md, docs/releases/versionhistory.md
Updated release information and versions
=> docs: updated release information and versions

docs/releases/frontend.md, docs/releases/overview.md, docs/releases/versionhistory.md, docs/releases/videobackend.md
=> feat: update documentation

docs/backend/service-configuration.md, docs/releases/messageservice.md, docs/releases/rocketchat.md, docs/releases/uploadservice.md, docs/releases/userservice.md
=> feat: add technical rocket chat username change

docs/releases/consultingtypeservice.md, docs/releases/userservice.md
=> feat: add migration documentation for keycloak roles

docs/backend/service-configuration.md
=> feat: add installation instructions for 2fa via otp

docs/releases/frontend.md, docs/releases/overview.md, docs/releases/userservice.md, docs/releases/versionhistory.md, docs/releases/videobackend.md
=> feat: update release documentation

docs/releases/consultingtypeservice.md, docs/releases/mailservice.md, docs/releases/overview.md, docs/releases/userservice.md, docs/releases/versionhistory.md, docs/releases/videobackend.md, docs/releases/videoservice.md
=> feat: update release

docs/frontend/extension.md
=> docs: add documentation for extension logic

website/siteConfig.js
=> change organizationName

.github/workflows/publish.yml
=> update gh-pages update workflow

.github/workflows/publish.yml
=> fix: workflow permission

.github/workflows/publish.yml
=> fix: deploy workflow
